### ISSUE TITLE
Trace matrix from tests and links to requirements/specifications?

### ISSUE THREAD

**Issue by davecap** [useblocks/sphinx-test-reports#12]
I've just started playing around with the needs system and this library. I was wondering if it is possible to create a trace matrix (table) to link other needs such as requirements/specs/implementations with test cases.

I am using pytest and have tried to load the test results via junit XML. It works, but I cannot seem to link the tests. Is there some way to declare each test manually, for example within the docstring of the test function itself? If I did that I could manually link them to other needs.

Alternatively, I assume you can add links dynamically when loading test data from XML. For example, I could link the test classname to some classname declared on the other need(s). I tried this but got an error:

```
.. test-report:: Test Report
   :id: TEST_REPORT
   :file: pytest_report.xml
   :tags: tests
   :links: [[tr_link('classname', 'classname')]]
```

The error was `Unknown dynamic sphinx-needs function: tr_link. Found in need: TEST_REPORT`

Ideally for my use case it would be best to declare each test as a need, but somehow also link that to the XML junit test suite results... is that possible?

**Comment by jakehader** [comment]
@davecap, I think I am having the same problem. I am also new to using this plugin but it seems that the `tr_link` function is not being dynamically added to `sphinx-needs` in:

https://github.com/useblocks/sphinx-test-reports/blob/20e1828a01b9085ec36e088d79cdd0b3c4f37efa/sphinxcontrib/test_reports/test_reports.py#L76-L111

Any insights @danwos?

**Comment by jakehader** [comment]
@davecap, I found that if I add the following lines to my `conf.py` file that it works:

```
from sphinxcontrib import test_reports
needs_functions = [test_reports.functions.tr_link]
```

**Comment by danwos** [comment]
Looks like a bug.
``tr_link`` should be available by default, as it gets registered during initialization of sphinx:

https://github.com/useblocks/sphinx-test-reports/blob/master/sphinxcontrib/test_reports/test_reports.py#L104

Will need to make some tests, but I guess the problem is in the used sphinx-needs function ``add_dynamic_function``.

@davecap: And yes, your use case is possible. That's the main reason why this extension was created and I have used it that way several times.

**Comment by danwos** [comment]
This bug is caused by a problem in sphinx-needs.
Which gets solved by https://github.com/useblocks/sphinxcontrib-needs/pull/289

I will try to make a new release for sphinx-needs asap.
So you will have to use ``sphinxcontrib-needs 0.6.3`` in your project.
If you don't want this, please use the workaround from @jakehader
